### ISSUE TITLE
AaRRghhh ! OU SONT LES PAGES ?!!

### ISSUE THREAD

**Issue by nemo2506** [francodacosta/grav-theme-foo#1]
Bonjour Franco Dacosta,
J'ai apprecié votre thème, j'ai même reconnu une grande qualité de mise en page et de style.
Je suis tout à fait débutant entre MARKDOWN et GRAV. Je remarque des thèmes d'une grande qualité en partage gratuitement et ils sont d'autant appréciable qu'il sont rare dans ce mode de partage.
Le monde GRAV est une grande découverte dans le monde du WEB que je pratique en tant que développeur depuis 9 ans. Facilité de mise en page avec un editeur MARKDOWN. Je pense le produire pour mes futures client.
Pourtant je ne comprends que vous ne partagiez pas vos PAGES puisqu'elle dépendent du travail en amont avec vos 4 templates. Actuellement il est est vrai que je ne connais pas la correspondance. J'avance pas à pas de découverte en découverte, quelques heures encore et je regretterais d' écrire ce message et de mettre en doute votre oeuvre. 
Toute fois je pense maintenant que c'est très frustrant.
Et je me demande si vous voulez donnez un partage d'un fichier default.md de MARKDOWN.
Merci pour votre lecture.
Cordialement

**Comment by francodacosta** [comment]
@nemo2506 

Nao entendi bem o que queres dizer, nao posso partilhar as paginas do tema, no entanto podes adicionar uma pagina que no grav admin  tens varias abas para configuracao da mesma

Qual e exactamente o tem problema?

**Comment by nemo2506** [comment]
> @nemo2506
> 
> Nao entendi bem o que queres dizer, nao posso partilhar as paginas do tema, no entanto podes adicionar uma pagina que no grav admin tens varias abas para configuracao da mesma
> 
> Qual e exactamente o tem problema?

Merci pour votre réponse,
J'attendais un exemple comme celui là:
```
---
title: PHOTOS
show_title: '1'
show_content: '1'
show_header: '1'
show_footer: '1'
site_theme: elegant
media_order: 'DSC01797.jpg,DSC03393.jpg,DSC01827.jpg,DSC02245.jpg,DSC02805.jpg,DSC02836.jpg'
columns:
    mobile: 12
    tablet: 4
    desktop: 4
---
```
Merci pour votre travail
